AUTOMATIC1111
stable-diffusion-webui
sd-webui
sd-webui-controlnet
stable-diffusion-webui-images-browser
sd-webui
sd-webui-cutoff
sd-webui-regional-prompter
sd-webui-tunnels
sd-webui-roop
pycloudflared
insightface==0.7.3
onnx==1.14.0
onnxruntime==1.15.0
opencv-python==4.7.0.72
tqdm
https://github.com/AUTOMATIC1111/stable-diffusion-webui
https://github.com/Iyashinouta/sd-model-downloader
https://github.com/Coyote-A/ultimate-upscale-for-automatic1111
https://github.com/Mikubill/sd-webui-controlnet
https://github.com/A-I-Channel/public-link /content/stable-diffusion-webui/extensions/tunnels
https://github.com/A-I-Channel/explorer-image
/content/stable-diffusion-webui/config.json